name: CI-CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello,Github Actions!"

      - name: Show runner Info
        run: |
         echo "Runner OS"
         uname -a

      - name: list files
        run: ls -a

      - name: Run a failing command (interntional)
        run: exit 1
