name: CI-CD Pipeline

on: 
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu:latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin

      - name: maven build
        run: mvn clean package

      - name: configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${secrets.AWS-ACCESS-KEY-ID}
          aws-secret-access-key: ${secrets.AWS-SECRET-ACCESS-KEY}
          aws-region: ap-south-1

      - name: login to ecr
        uses: docker/login-action@v3
        with:
          registry: 535002872949.dkr.ecr.ap-south-1.amazonaws.com/task-dashboard

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tag: 535002872949.dkr.ecr.ap-south-1.amazonaws.com/task-dashboard:${{ github.sha }}
          
      
